services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    pull_policy: build
    networks:
      - inception_net
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    pull_policy: build
    networks:
      - inception_net
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    restart: on-failure
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_NAME: ${MYSQL_NAME}
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}

      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

      WP_SECOND_USER: ${WP_SECOND_USER}
      WP_SECOND_EMAIL: ${WP_SECOND_EMAIL}
      WP_SECOND_PASSWORD: ${WP_SECOND_PASSWORD}

  nginx:
    container_name: nginx
    image: inception-nginx
    build:
      context: ./requirements/nginx
    pull_policy: build
    ports:
      - "443:443"
    networks:
      - inception_net
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    restart: on-failure
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yutsasak/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yutsasak/data/wordpress

networks:
  inception_net:
    driver: bridge
